# Setup
title:               "Kane Toh"
tagline:             'My Tagline'
description:         "Kane's blog"
url:                 'https://kane9530.github.io'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Kane Toh
  url:               https://twitter.com/kane953o
  email:             kane9530@hotmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
